apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{- if (lookup "v1" "Service" "ingress-nginx" "ingress-nginx-controller")}}
  lookup: "Serviço existe"
  {{- end }}
