apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  {{- with .Values.favorita }}
  bebida: {{ .bebida }}
  comida: {{ .comida }}
  release: {{ $.Release.Name }}
  {{- end }}
  caneca: {{ .Values.favorita.caneca }}
