apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  bebida: {{ .Values.favorita.bebida | repeat 5 | quote}}
  comida: {{ .Values.favorita.comida | upper | quote}}